name: "Feature Branch: Build & Test"
on: 
    push:
        branches:
            - '**'
            - '!devel'
            - '!*release*'
            - '!*hotfix*'
            - '!main'
    workflow_dispatch:
    
jobs:
  feature-branch-build-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Feature Branch Build and Test
        run: echo "Feature Branch: Build & Test"
        
        
        
        
        
        