name: Deploy Stage by tag

on:
  release:
     types: [published]
     
jobs:
  stage-deploy:
       
    runs-on: ubuntu-latest
    if: "contains(github.ref, 'Stage')"
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Stage by tag
        run: echo "Deploy Stage by tag"
