name: Deploy Live by tag

on:
  release:
     types: [published]
  workflow_dispatch:
     
jobs:
  live-deploy:
       
    runs-on: ubuntu-latest
    if: "contains(github.ref, 'main')"
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Live by tag
        run: echo "Deploy Live by tag"
