name: "Stage: Deploy"
on: 
    workflow_dispatch:

jobs:
  stage-deploy:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Stage Deploy
        run: echo "Stage: Deploy"
        
        
        
        
        
        